FROM eclipse-temurin:21-jdk-jammy

WORKDIR /app

COPY target/*.jar /app

COPY ccserver/ /app/ccserver

EXPOSE 7000

# wird in docker-compose.yml überschrieben
CMD ["java", "-cp", "/app/g2gnet-1.0-SNAPSHOT.jar", "org.geooo.CCServer"]