FROM eclipse-temurin:21-jdk-jammy

RUN apt-get update && apt-get install -y \
    tigervnc-standalone-server \
    tigervnc-common \
    fluxbox \
    libxrender1 \
    libxtst6 \
    libxi6 \
    libgl1-mesa-glx \
    libgtk-3-0 \
    xfonts-base \
    wget \
    unzip \
    && rm -rf /var/lib/apt/lists/*

RUN wget -O /tmp/javafx.zip https://download2.gluonhq.com/openjfx/21.0.1/openjfx-21.0.1_linux-x64_bin-sdk.zip && \
    unzip /tmp/javafx.zip -d /opt/ && \
    mv /opt/javafx-sdk-21.0.1 /opt/javafx && \
    rm /tmp/javafx.zip

WORKDIR /app

COPY target/*.jar /app
COPY client/res/ /app/client/res

COPY vnc-startup.sh /app/vnc-startup.sh
RUN chmod +x /app/vnc-startup.sh

EXPOSE 5901
EXPOSE 7000

# wird in docker-compose.yml überschrieben
CMD ["./vnc-startup.sh"]